package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Поиск текста на странице")
    void generatedTest() {
        step("Открыть 'https://awem.com/'", () -> {
            step("// todo: just add selenium action");
        });

        step("Найти вкладку \"Игры\"", () -> {
            step("// todo: just add selenium action");
        });

        step("Нажать на неё", () -> {
            step("// todo: just add selenium action");
        });

        step("Убедиться что есть необходимые игры", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://awem.com/'", () ->
            open("https://awem.com/"));

        step("Page title should have text 'Awem Games'", () -> {
            String expectedTitle = "Awem Games";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://awem.com/'", () ->
            open("https://awem.com/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}